# Generated by Django 4.2.5 on 2026-05-03 07:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "Id",
                    models.UUIDField(
                        db_column="Id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "CustomerId",
                    models.UUIDField(blank=True, db_column="IdCustomer", null=True),
                ),
                (
                    "SalesChannel",
                    models.CharField(db_column="SalesChannel", max_length=100),
                ),
                ("Status", models.CharField(db_column="Status", max_length=50)),
                (
                    "Total",
                    models.DecimalField(
                        db_column="Total", decimal_places=2, max_digits=14
                    ),
                ),
            ],
            options={
                "db_table": '"Sales"."Orders"',
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "Id",
                    models.UUIDField(
                        db_column="Id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                ("OrderId", models.UUIDField(db_column="IdOrder")),
                ("ProductId", models.UUIDField(db_column="IdProduct")),
                ("Quantity", models.IntegerField(db_column="Quantity")),
                (
                    "Price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, max_digits=12
                    ),
                ),
            ],
            options={
                "db_table": '"Sales"."OrderItems"',
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "Id",
                    models.UUIDField(
                        db_column="Id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                (
                    "CustomerId",
                    models.UUIDField(blank=True, db_column="IdCustomer", null=True),
                ),
                (
                    "Status",
                    models.CharField(
                        db_column="Status", default="DRAFT", max_length=30
                    ),
                ),
                ("ValidUntil", models.DateTimeField(db_column="ValidUntil")),
                ("Notes", models.TextField(blank=True, db_column="Notes", null=True)),
            ],
            options={
                "db_table": '"Sales"."Quotes"',
            },
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "Id",
                    models.UUIDField(
                        db_column="Id",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "CreatedAt",
                    models.DateTimeField(auto_now_add=True, db_column="CreatedAt"),
                ),
                ("ProductId", models.UUIDField(db_column="IdProduct")),
                ("Quantity", models.IntegerField(db_column="Quantity")),
                (
                    "UnitPrice",
                    models.DecimalField(
                        db_column="UnitPrice", decimal_places=6, max_digits=18
                    ),
                ),
                (
                    "SupplierAvailableQty",
                    models.IntegerField(db_column="SupplierAvailableQty", default=0),
                ),
                (
                    "LocalAvailableQty",
                    models.IntegerField(db_column="LocalAvailableQty", default=0),
                ),
                (
                    "AvailabilityCapturedAt",
                    models.DateTimeField(
                        blank=True, db_column="AvailabilityCapturedAt", null=True
                    ),
                ),
                (
                    "DeliveryMode",
                    models.CharField(db_column="DeliveryMode", max_length=50),
                ),
                (
                    "Quote",
                    models.ForeignKey(
                        db_column="IdQuote",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Items",
                        to="sales.quote",
                    ),
                ),
            ],
            options={
                "db_table": '"Sales"."QuoteItems"',
            },
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["CustomerId", "Status"], name="IX_Quotes_Customer_Status"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["ValidUntil"], name="IX_Quotes_ValidUntil"),
        ),
        migrations.AddIndex(
            model_name="quoteitem",
            index=models.Index(fields=["Quote"], name="IX_QuoteItems_Quote"),
        ),
        migrations.AddIndex(
            model_name="quoteitem",
            index=models.Index(fields=["ProductId"], name="IX_QuoteItems_Product"),
        ),
    ]
